package v1alpha2

import (
	"github.com/blang/semver"
)

type Version struct {
	semver.Version `json:",inline"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Version) DeepCopyInto(out *Version) {
	*out = *in
	out.Version = semver.MustParse(in.Version.String())
}
