on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build latest
      run: "docker build -t goharbor.io/harbor-operator:latest"
