on:
  push: {}
  pull_request:
    branches:
    - master

jobs:
  go-dependencies:
    runs-on: ubuntu-latest
    name: Ensure dependencies are up to date
    steps: 
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - run: go mod tidy
    - run: go mod vendor
    - name: Check diff
      uses: fnkr/github-action-git-bash@v1
      with:
        args: test -z "$(git diff-index --diff-filter=d --name-only HEAD -- 'vendor' | grep -v 'vendor/modules.txt')"

  generated-files:
    runs-on: ubuntu-latest
    name: Ensure dependencies are up to date
    steps: 
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - run: make generate
    - name: Check diff
      uses: fnkr/github-action-git-bash@v1
      with:
        args: test -z "$(git diff-index --name-only HEAD --)"

